# This is a basic workflow to help you get started with Actions

name: CI Demo

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main", "feature/branch" ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world, steve!
      - name: Running a custom script
        run: | 
           ls -al

      #Add azure stuff
      - name: Log in with Azure Action
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
       
      - name: Run AZ command
        run: | 
          az account show
          az group list    
      
      - name: Get K8s context
        uses: azure/aks-set-context@v3
        with:
          resource-group: aks-1_group
          cluster-name: aks-1
       
      - run: |
          kubectl create namespace githubrg 

      - run: |
          kubectl apply -f pod.yaml     

      # Runs a set of commands using the runners shell test 2
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: check java version
        run: java -version
      - name: gradle build
        run: gradle build
      - name: gradlew build
        run: ./gradlew build
      - name: docker version
        run: |
          docker -v
          docker
          docker images -a
      - name: docker build
        run: |  
          docker build . -t demo-kotlincreatedbysteve:1.0.0
          docker tag demo-kotlincreatedbysteve:1.0.0 spostek/demo-kotlincreatedbysteve:1.0.0 
          docker images -a
      - name: docker login
        run: docker login --username ${{ secrets.DOCKERHUBUSER }} -p ${{ secrets.DOCKERHUBPASSWORD }}
      - name: docker image push
        run: docker push spostek/demo-kotlincreatedbysteve:1.0.0   
